/* Bản dịch tiếng Anh của sách "Mật Mã Tự Do" — Phong Menly.
   Khoá theo data-tr="<id>" trong doc-sach.html.
   Dịch theo lối kể tự nhiên của tác giả (câu ngắn, giọng thật) để AI đọc lên nghe đúng tông.
   File này sinh tự động từ các đợt dịch — sửa câu chữ trực tiếp ở đây được. */
window.BOOK_EN = {
  0: "START 01",
  1: "THE FREEDOM<br>CODE",
  2: "AFFILIATE × AI",
  3: "From <b>one</b> to <b>number one</b>",
  4: "Written by <b>Phong Menly</b>",
  5: "Acknowledgements",
  6: "This book was written by someone who hasn't made it big yet.",
  7: "That's the first thing I want you to know before you read anything else.",
  8: "I'm not writing from the top of the mountain looking down. I'm sitting in the middle of the journey, with the same old laptop, doing exactly what I'm about to describe on every page.",
  9: "This journey started with a name I'll never forget: Sơn Piaz.",
  10: "He wandered all over America — not as a tourist, but to find one answer: how can an ordinary person become truly free on the internet?",
  11: "I was lucky enough to walk part of that road with him.",
  12: "From the real conversations, from sitting there watching him build a system from zero, from his willingness to go and to try — that's where I understood what I'd been missing.",
  13: "That's where <b>START 01</b> came from.",
  14: "That's where <b>affitor</b> came from, and the affiliate network being built day by day.",
  15: "And that's where this book in your hands came from.",
  16: "What we're aiming at is one specific road: one person, one million dollars — no hundred-person team, no office, no heavy machinery.",
  17: "I haven't gotten there yet.",
  18: "But I'm walking. And I wrote this both to put my own journey in order, and to invite you to walk with me.",
  19: "If you're searching for a direction too, if you can't name what's missing, if you've been trying and seeing nothing — this is the book I want to give you. Not because I'm ahead of you, but because I'm on the same road.",
  20: "Let's begin.",
  21: "— Phong Menly",
  22: "A Note About This Book",
  23: "This is the first manuscript in the <b>START 01</b> series, put together from my own real journey through affiliate marketing.",
  24: "Every story in this book is a <b>true story</b>, retold in a natural, close-up voice so the lessons come out of real life instead of theory.",
  25: "<b>Author:</b> Phong Menly. <b>Produced:</b> with the help of my “Second Brain” system and artificial intelligence. <b>Images and design:</b> created with AI.",
  26: "Opening Words",
  27: "At twenty, I made a vow.",
  28: "“Either I succeed, or I die on the way to succeeding.”",
  29: "I meant it. My mouth, my chest full of fire — I believed every word. My friends stood and watched me walk ahead. Back then I thought that was what made me different.",
  30: "Then ten years passed. I looked back and started doubting myself. My shoulders ached. I kept pushing and never found the way out. I drifted into the fog — and fell into somebody else's game.",
  31: "Then came a family. The wild horse was slowly covered over by time and responsibility. A few more years of letting go. And just like that, I forgot my own dream.",
  32: "This book starts on the day I remembered.",
  33: "— Phong Menly",
  34: "The Freedom Code · Phong Menly",
  35: "CONTENTS",
  36: "I",
  37: "The Wild Horse Loves to Explore",
  38: "First failure · A lesson about choosing",
  39: "II",
  40: "The Traffic Map",
  41: "The key that opens the door to freedom · 5 legendary steps",
  42: "III",
  43: "Pride & The Long Slide Down",
  44: "Celebrating early, and the trap of resting",
  45: "IV",
  46: "Cash Flow Drives Traffic",
  47: "What to do when the first small wins arrive",
  48: "V",
  49: "The System's Game",
  50: "A one-person empire running the whole machine",
  51: "Affiliate × AI · Start 01",
  52: "Chapter 1 · The First Failure",
  53: "The Wild Horse<br>Loves to Explore",
  54: "This road takes the most years of all.<br>There's no way around it — unless you have criteria.",
  55: "Every wrong turn costs three years of your youth",
  56: "Chapter 1 · The Wild Horse Loves to Explore",
  57: "I'm writing this book before I've actually become financially free.",
  58: "That has to be said straight out, right at the start. Not out of modesty. Because it's the most important thing you need to know. I'm not writing from the top of the mountain looking down. I'm still walking, writing down what I know as I go — what I've found, what I've tried, what I've tripped over.",
  59: "Here's what I know: I've found the right direction. The lifeblood of the <b>one-person</b> business model — stripped down, simple, brutally effective, and capable of beating a company of a hundred people.",
  60: "But to learn that, I spent years being a <b>wild horse</b>.",
  61: "A wild horse loves to explore. I could start anything — sell this product, try that model, hear someone talk well and jump straight in. I never completely lost. But I never really won either. There was always a limit — an invisible ceiling that no amount of extra effort could get me past.",
  62: "Back then I thought the problem was that I wasn't good enough, wasn't working hard enough. The truth was: <b>I was choosing the wrong model and the wrong road</b>. Nobody told me that. Everyone around me said the same single thing: <i>“Just do it better. Serve your existing customers better.”</i>",
  63: "Later I understood: that wasn't advice. That was the trap. Because <b>the customers and the demand were already out there</b> — the market had been ready for a long time. What I lacked wasn't skill. It was <b>the choice</b>.",
  64: "I once heard someone say business is about solving the market's problems. I didn't understand that line until I actually ran into it — the most painful way possible.",
  65: "The person who gave me that answer was <b>Sơn Piaz</b>. He isn't someone who sits around teaching theory. He actually went — literally and figuratively. He left Vietnam and wandered across America, not as a tourist, but to find one answer: <i>how can an ordinary person become truly free on the internet?</i> He met this person, learned from that one, tried things and dropped them, dropped them and tried again — until he saw the road. Not a road someone else had drawn for him, but one he walked out on his own two feet. And he built something I'd never seen anyone in Vietnam pull off: <b>a real affiliate system.</b>",
  66: "I went to one of his events — 250 people, all of them what I'd call <b>heavy hitters</b>. They had influence, credibility, their own projects. But when I tried to lean in and listen, what I realised was this: they were talking about finance, Google Ads, YouTube — and they seemed to be there not to learn something new, but to see familiar faces from their own industry. Because Sơn Piaz was the one leading the way in affiliate, the whole hall treated it like a reunion. As for AI back then — nobody saw much potential in it. It sat neatly under three words: <b>Not Yet Explored</b>.",
  67: "And me? I was an unemployed boss working someone else's job, lost in my own life, looking for a way out. I didn't understand much — same as plenty of other people in that room full of lofty jargon. But I got lucky: <b>I caught three hidden commands</b> — the kind most people barely notice.",
  68: "Command 1 · Sơn Piaz",
  69: "“Why is it that someone putting in the same effort as you — sometimes less — ends up more successful? Because they're simply doing something different from you. They picked the right direction, the right trend, the right market, the right demand.”",
  70: "That line hit me square in the face. Not because it was new — but because I knew it was true.",
  71: "Command 2 · Tony Triệu",
  72: "“You're going to put in the work either way. So why not think about going global? Pick the hard thing from the start — everything after that gets easier. And work alongside someone who already has a project, already has experience. You'll learn a hundred times more than paying for a course.”",
  73: "Command 3 · Hoàng Nam",
  74: "“Instead of chasing attention, build the system first — use a content matrix and email marketing. Always pick the fastest option so you can measure best. And focus on your strength: the thing you're most confident in.”",
  75: "Three commands. Not a curriculum. Not an expensive course. Just three sentences most people walk right past — and they completely changed how I saw my own road.",
  76: "And that was the moment I looked at the map of four unexplored affiliate markets — and for the first time in years, I knew which one I had to pick.",
  77: "— Phong Menly",
  78: "Make your choice",
  79: "E-Commerce",
  80: "Shopee",
  81: "TikTok Shop",
  82: "Fashion",
  83: "Food",
  84: "Mobile Apps",
  85: "Dropshipping",
  86: "Services",
  87: "Beauty",
  88: "Health Care",
  89: "Supplements",
  90: "SaaS",
  91: "Coaching",
  92: "Spa · F&B",
  93: "Finance",
  94: "Finance",
  95: "Forex",
  96: "Crypto",
  97: "Insurance",
  98: "Stocks",
  99: "Investing",
  100: "AI · Technology ✦",
  101: "AI Tools",
  102: "AI Agents",
  103: "Automation",
  104: "No-Code",
  105: "AI SaaS",
  106: "AI Affiliate",
  107: "★ Newcomers have the edge here",
  108: "I went through three markets — never a total loss, but never a real win either. Each one had its own wall, and I only saw it after hitting it hard enough to hurt.",
  109: "<b>E-Commerce</b> — selling products, running ads, optimising listings. Easy to get into, easy to convert, easy to measure. But commission is paid <b>once</b>, price competition is brutal, your capital gets stuck in inventory, and logistics eats the margin. It doesn't take much deep thinking — but you have to keep changing with consumer trends, forever. Stop running ads and the income stops. The most expensive lesson: <b>that income doesn't scale.</b>",
  110: "<b>Services</b> — content, consulting, coaching, running projects. Common in Vietnam and abroad, and you can start with zero capital. But this is an industry <b>for people with real expertise and real credibility</b>: easy to start, easy to open — but hard to run, and the costs keep climbing. It demands constant mental effort, competition is fierce, and scaling is hard before you have the capacity. More clients just means more work. I wasn't free — I'd only <b>changed bosses</b>.",
  111: "<b>Finance</b> — investing, stocks, forex, fintech. This one is <b>for the sharp and the capable</b> — it demands real intellect and emotional control. You need to be the marketer more than the player. Commissions are high, competition is moderate — but the risk is severe, the real value is thin, and it's genuinely dangerous for both the referrer and the referred when neither knows enough. I was just playing <b>gambling in a suit</b>.",
  112: "Chapter 1 · Selection Criteria",
  113: "WIN CRITERIA",
  114: "Project",
  115: "WIN PROJECT",
  116: "Right direction · Right interest · <b>Fast to results</b>",
  117: "Unlimited · Easy to scale · A <b>3 – 6 – 10 year</b> runway ahead",
  118: "Easy to start · Plenty of content angles to introduce &amp; promote",
  119: "You get better over time · Sharper · <b>Credibility grows</b>",
  120: "Passive cash flow · Continuously updated · Real value to the market",
  121: "Product",
  122: "WIN PRODUCT",
  123: "<b>$150 – 600 per user</b> minimum",
  124: "Traffic &gt; <b>200,000 / month</b>",
  125: "<b>12-month recurring</b> or lifetime — with clear payouts",
  126: "Recently launched · Regularly updated · Plenty of demand",
  127: "Easy to recommend · Brand actively supports you · <b>Booking available</b>",
  128: "Marketing",
  129: "WIN MKT",
  130: "Free credit, or credit support available",
  131: "Compelling offer · No long chain of steps to introduce it",
  132: "You genuinely like it &amp; feel <b>excited</b> every time you use it",
  133: "Users get <b>immediate results</b> when they use it",
  134: "Run a test → plenty of positive feedback, little effort",
  135: "Three markets. Years of my life. Every time it felt like I was on the right track — until I hit <b>the invisible ceiling</b> and couldn't get past it. And now you know why I chose <b>Affiliate × AI</b> for my one-person business.",
  136: "<i>What about you? Choose your road.</i>",
  137: "I believe that in three years every dream you have can be real — instead of ten years of grinding. The will may still be there, but your health, your sharpness and your relationships keep thinning out.",
  138: "If it doesn't meet these criteria — I simply don't do it. I like being an entrepreneur, and I only share in the area I'm genuinely best at.",
  139: "— Phong Menly",
  140: "Chapter 1 · A Lesson About Choosing",
  141: "Making<br>The Decision",
  142: "The moment you make a decision — your fate starts taking shape.<br>Say yes to the thing that fills you with energy.",
  143: "Choose the road that makes you want to move forward every day",
  144: "Every time you make a decision — your fate starts taking shape.",
  145: "The first thing I did after that event wasn't to make a plan, find a mentor or buy a course. I looked at how much money was left in my pocket.",
  146: "That's the most honest question anyone starting over has to answer: <i>If I have no income for the next three to six months — can I survive?</i>",
  147: "If that were you, what would you do?",
  148: "I know what most people answer. Panic. Worry. Fear of missing the chance. And salespeople know that perfectly well — they aim straight at the pain, crank up the urgency, and get you confused enough to decide before you've actually thought.",
  149: "But I'd already walked every one of those roads. I understood why I hadn't broken through in ten years. Not from lack of effort. Not from lack of passion. Simply <b>from not choosing right at the very start</b>.",
  150: "This time I set myself a rule: <b>12 hours</b> to decide — no more. Because the longer I sat with it, the more I'd doubt myself. And once I'd truly decided, I trusted that everything would start lining up behind me.",
  151: "I had to pick something I could <b>genuinely be good at within three years</b> — with an international outlook, real experience, and technology as leverage. I couldn't go around in circles one more time.",
  152: "And right at that moment — my wife was about to give birth.",
  153: "Ten years of building things. So many projects, so many roads tried. And here I was, standing with no real job, with a child about to arrive. Someone else might call that a burden. To me — it was <b>fuel</b>.",
  154: "I opened YouTube and rewatched the first videos on <b>Sơn Piaz</b>'s channel. He was building his career <b>alone in America</b> — no company behind him, no support team. One person, one screen, and a system he'd built from nothing.",
  155: "I thought: <i>He did it. Why can't I?</i>",
  156: "And I decided. Not because I was sure I'd succeed. Because this time I had actually chosen — no hesitating, no waiting for one more perfect moment.",
  157: "“Are you living — or just existing?”",
  158: "I've carried that line with me through this whole journey.",
  159: "After I decided — the door really did open. No drama. No fanfare. Just the first time in ten years that I knew I was heading the right way.",
  160: "Listen, my friend — whether you walk this road with me or not, keep following along. By the end of this book you'll know what you actually need and what your next step is. I'll take you through it step by step — including the craziest things I went through — so you can cut down the time it took me by a long way.",
  161: "— Phong Menly",
  162: "Part II · The Key",
  163: "The Traffic Map",
  164: "Five legendary steps that open the door to freedom.<br>This is the most important chapter.",
  165: "ONE-PERSON BUSINESS PLAN",
  166: "A business plan for a one-person company",
  167: "Simple. Direct. Nothing flashy. This is the plan I wrote out right after deciding — on a sheet of paper, in a coffee shop, with no money in my pocket and one laptop.",
  168: "After the decision —<br>I had five things clear:",
  169: "Industry",
  170: "<b>AI Affiliate</b> — an opening market where newcomers still have a big edge",
  171: "Market",
  172: "<b>Go Global · Vietnam → US</b> — using the fact that I was working with Sơn Piaz, aiming straight at the international market",
  173: "Goal",
  174: "<b>The first $1,000</b> in 3–6 months — enough to live on, enough to prove the direction is right",
  175: "Model",
  176: "<b>1 person + 1 computer</b> — no office, no staff, no fixed costs. The coffee shop is the office.",
  177: "Strategy",
  178: "<b>One road only</b> — nothing else tried, nothing run in parallel. Everything goes here.",
  179: "“When you only have one road — you've got no reason left to hesitate.”",
  180: "Part II · Skill 01 / 05",
  181: "Follow the Flow of<br>Those Who Made It",
  182: "You don't need to do more — you need to walk straighter.<br>One right map beats a hundred books.",
  183: "Here's the thing — I was taught that to succeed I had to do a lot of things and collect a lot of experience. Until I looked at this map… I only needed to do less than a third of what I thought I knew. And the good part — it's all laid out along a very detailed route.",
  184: "It's hard to walk when you don't have a road.",
  185: "I was handed an affiliate marketing map with five steps — from zero to the first order.",
  186: "— Strange, right? Shouldn't the goal be something bigger? Why “the first order”?",
  187: "The challenges I had to clear, one at a time:",
  188: "And I needed something to turn what I had into a process of my own.",
  189: "Whoever gets the customer to that first click — wins.",
  190: "I'd bet everyone wants results. But what the result actually is, how much, how to get there — when it comes to answering that for yourself, almost nobody really looks. The rush, and the market pulling you along, makes you forget all of it.",
  191: "Seven restless days went by. What I faced daily were the looks from people around me. I'd cut myself off from everyone — just shut myself into a corner of a coffee shop. I ordered one drink, showed up so punctually that the owner knew exactly where I'd sit.",
  192: "Back then I couldn't see far ahead. I just followed the steps I'd been given — every day my work was only this:",
  193: "Build · A/B Testing · Click · Sale",
  194: "— If it were you, what would you do?",
  195: "Step 1 — Choose the AI Affiliate road",
  196: "I started from what I didn't know. I just started with AI — asking questions. Learning how to ask, learning how to take screenshots, solving problems myself. Whatever I was doing, I'd ask AI directly what my next step should be.",
  197: "— Oddly enough, I still do it this way. I ask silly questions like: “What is this? How do I do it? Why do I even need this?” — but that's the first thing I do.",
  198: "Step 2 — Build a sales page &amp; find a winning product",
  199: "To win this game you need a sales page. <b>This is the closest thing to the money.</b> Plenty of people run off to build channels — but where the money actually comes from, they're mostly blind to.",
  200: "We keep doing something up in the clouds — with no clear target: what business, what product?",
  201: "I once built 27 TikTok channels. No fewer than 10 YouTube channels. And nobody ever told me this. Looking back now…",
  202: "It's almost funny — I used to think I'd go online, build a personal brand, preach some wisdom, collect followers and then sell. For a while I even played the hard-luck card, the leaving-the-city-for-the-countryside story. But where the money would actually come from, I had no idea.",
  203: "— Have you ever done that?",
  204: "This is where you stop depending on any platform.<br>Your sales page — you get to set the rules of your own game.",
  205: "Think about it: you're marketing on a platform — but when a customer wants to check your information, they have to pay, or there's no data at all.",
  206: "With your own sales page, you can sell any product, market to anyone — on any platform. <b>Few people know this</b>, because it used to be that only big companies had the budget. But now — with AI and AI agents — it's a different story.",
  207: "You can't create a five-star customer experience if you've never experienced five-star service yourself.",
  208: "If you've never built a sales page, try making your first one today:",
  209: "Click Here",
  210: " — a guide to building your first sales page",
  211: "Don't worry about a perfect website — one page of your own is enough. Just keep moving forward.",
  212: "Build a sales page",
  213: "Understand it",
  214: "Level up",
  215: "Course bundle",
  216: "Part II · Skill 02 / 05",
  217: "Pick a Winning Product",
  218: "Commission from <b>12 months to lifetime</b>",
  219: "Can be <b>applied immediately</b> in practice",
  220: "<b>Continuously upgraded</b>",
  221: "Pays the <b>highest commission, 25%–50%</b>",
  222: "Turns you into <b>an assassin</b>",
  223: "Choose your product the way you'd choose a weapon — with the wrong weapon, every skill is useless.",
  224: "If you don't have a product yet — <b style=\"color:var(--ink);\">that's fine.</b> I have two options, and I'll support you wherever you join:",
  225: "1. KOL AI Affiliate Network",
  226: "Mr. Phong Menly &amp; the KOL AI SYSTEM community",
  227: "Click to join →",
  228: "2. Affitor",
  229: "Mr. Sơn Piaz",
  230: "Click to join →",
  231: "Top of mind in affiliate marketing &amp; the thinking behind building a one-person business to a million dollars. I've been lucky enough to work with Sơn Piaz — and I'll support you free of charge.",
  232: "But… yes, there's always a “but”. You need to start with products that cost nothing. Products like that — if you find them, they have to come with your affiliate link attached.",
  233: "Think in terms of leveraging free platforms, well-known products, and products that keep getting upgraded.",
  234: "Google is always ambitious. As I'm writing this to you, OpenAI is the first name in the world famous for AI. Those two names took me from zero.",
  235: "I picked ten promising projects and products. But the one that made me the most money turned out to be the product everyone was already using most.",
  236: "Anything free that's also useful — people will always choose it first. Nobody wants to spend money.",
  237: "The product accounts for 60% of your odds of winning. You wouldn't buy this book if you hadn't read chapter 1 first — that's exactly how I sell it, and it's how you'll sell your product too.",
  238: "Famous, free products usually don't have an affiliate link for you to promote. But with sharp thinking — you can create your own link by building things around it that help people actually use that product.",
  239: "Browser Extension",
  240: "(Extension)",
  241: "Sell beer, serve peanuts with it — sell seafood, serve the dipping sauce.",
  242: "Someone selling a course bundles a tool with it — the main product is still the course.",
  243: "It still sits in the services space with few players — but that's the way in.",
  244: "You work in affiliate, you work on the software with reverse thinking — share the experience, throw in a tutorial video, sell to a million people.",
  245: "<b>Just keep going like that.</b>",
  246: "Personal Brand",
  247: "With a personal brand, what other people think of you matters a great deal. That's why I didn't cast myself as a <em>teacher</em>.",
  248: "As a teacher, I wouldn't be able to run a business and sell the products I want. Same for you — <b>your freedom is your decision.</b>",
  249: "Keep walking, and you'll arrive.",
  250: "Part II · Skill 03 / 05",
  251: "Building<br>Traffic",
  252: "<b>Affiliate Marketing = Industry &amp; Product</b> (Steps 1+2) <b>+ Marketing</b> (Step 3). There are four methods — pick one now, and avoid jumping into resources you can't reach yet:",
  253: "Free Traffic",
  254: "When you're just starting",
  255: "Affiliate Network",
  256: "When you have a flow of people",
  257: "No Face",
  258: "When you want to replicate / stay anonymous",
  259: "Conversion",
  260: "When you want the money to come in",
  261: "Before you talk about building a channel or doing anything else — know what resources you actually have, and which one genuinely fits you.",
  262: "The variables for picking the road that suits you right now:",
  263: "<b>Easy + Fast:</b> from 0 → your first $1,000",
  264: "<b>Has Customers + Fast:</b> $1,000 → $10,000",
  265: "<b>Easy + Brand Building:</b> build a community, nurture it long term",
  266: "<b>Has Customers + Brand Building:</b> $10,000 → $100,000",
  267: "The traffic map has three layers: <b>Attract → Credibility → Convert</b>",
  268: "<b>Bonus:</b> To sell a product you need someone famous. An ordinary person sells by riding <b>a famous product.</b>",
  269: "Listen, my friend,",
  270: "Now you know why you've been lost — rushing at the hard things when what you need is cash flow. Whatever the world is updating, let them — just pay attention to what the person you follow is using, and use it too.",
  271: "One step at a time.",
  272: "Track 1 — Complete Beginner",
  273: "New, no product, no reputation. Goal: <b style=\"color:var(--ink);\">create your first cash flow — as fast as possible.</b>",
  274: "1 · A dirt-cheap entry product (Product $2)",
  275: "Don't try to sell a course worth millions. Make a practical digital product (a template, a prompt sheet, a document) worth about $2. The buyer doesn't have to think — extremely easy to close.",
  276: "2 · Drag-and-drop AI tools — 1 landing page",
  277: "AI image &amp; AI video (Midjourney, Higgsfield) for content that pulls people in. Build <b>one single landing page</b> selling that one entry product.",
  278: "3 · Traffic — viral posts + 1 affiliate link",
  279: "Short TikTok videos and viral posts to pull viewers in. Pick exactly <b>one quality affiliate product</b> — don't scatter links everywhere.",
  280: "4 · Close manually — direct touch",
  281: "Pull customers into a Facebook group or your personal Facebook. <b>Message them one-on-one</b> and advise them directly. In the early stage, human interaction is the key to orders.",
  282: "5 · Recruit partners (team at 35%–50%)",
  283: "Be willing to give a high cut to people selling alongside you so revenue multiplies fast — with no fixed salary.",
  284: "The Affiliate Marketing Code",
  285: "Track 2 — Already Have a Foundation",
  286: "You already have a customer base &amp; steady cash flow. Goal: <b style=\"color:var(--ink);\">automate, raise cart value and optimise operations.</b>",
  287: "1 · Upgrade the product (Product $5–$10)",
  288: "Raise the value of the digital product by building in smarter solutions.",
  289: "2 · Automate conversations — AI agent",
  290: "<b>Chatbot / Facebook agent</b> replaces sitting on chat 24/7. An AI agent sends emails itself and sorts data from SePay. <b>AI vibe coding</b> helps build sales pages &amp; products.",
  291: "3 · Expand the system — 5–10 sales pages",
  292: "Run A/B testing to find the best-converting template. Manage 10 affiliate links to diversify passive income.",
  293: "4 · High-end conversion — one-to-many",
  294: "<b>VSL video</b>: sells automatically even while you sleep. <b>Webinar / livestream</b>: close in bulk instead of advising one person at a time.",
  295: "5 · Deep technical skills",
  296: "<b>Miro</b>: design your operating flow. <b>AI vibe coding</b>: write your own micro-tools (SePay connections, automatic webhooks). Professional screen-recording software to package your process into a digital asset.",
  297: "The Traffic Code",
  298: "The Biggest Mistake About Personal Branding",
  299: "<b>The mistake:</b> building a personal brand in order to sell.",
  300: "The right thinking is: sell, share the experience, retell what you actually did — <b>that is what really builds a personal brand.</b>",
  301: "People don't want to be preached at. They might cheer you on — but they won't buy.",
  302: "So your job isn't to write more or film more — it's to <b>let people see what you can actually do.</b>",
  303: "This is the line between someone who gets followed and someone who gets paid. You need both — but you have to know which comes first.",
  304: "Bottom line: start with the easiest thing",
  305: "<b>Pick a topic + a formula:</b> top lists · updates · comparisons · tutorials · creating a new product.",
  306: "Execute and grow from the smallest thing to the biggest:",
  307: "Write a how-to post — Facebook + attach the link",
  308: "Make a short video — CTA with the link",
  309: "Make a long video — CTA with the link",
  310: "You don't need the complicated steps yet — just try. Some expert will say, “How is that ever going to convert?” Let them.",
  311: "Whatever you know first, do first. Whoever reaches that click faster — wins.",
  312: "Part II · Skill 04 / 05",
  313: "Give Gifts,<br>Create Leads",
  314: "A gift is a weapon — not to buy someone off, but to become indispensable in your customer's life.",
  315: "📂 Open the Marketing Resource Library",
  316: "<b>The power of information and market demand.</b> As long as you have the information first — you're always the one who wins.",
  317: "I know this is hard for you. But I think it's genuinely necessary — go international, widen your view, gather the valuable resources other people don't have yet.",
  318: "A gift is the weapon that brings you and your customer closer together.",
  319: "A gift can:",
  320: "Grow the number of interested people in your group",
  321: "Help your posts go viral",
  322: "Position you as an expert worth following",
  323: "What can the gift be?",
  324: "Tutorial video",
  325: "Free",
  326: "A packaged process",
  327: "Free",
  328: "Top 10 tools",
  329: "Free",
  330: "Free AI app",
  331: "Free",
  332: "= Thousands of customers pouring into your sales page",
  333: "The Gift Packaging Strategy",
  334: "Remember: information is the gift. Anything you share can become a gift if it solves the recipient's problem.",
  335: "POST",
  336: "Share useful information → that's a gift in itself",
  337: "VIDEO",
  338: "A short video showing one specific thing in practice",
  339: "DOCS",
  340: "Google Docs / Notion — click the link and get it instantly",
  341: "APP",
  342: "An affiliate link guide with a clear process",
  343: "ZOOM",
  344: "A free hands-on session → later refined into a $2 product",
  345: "Try this: build one gift you can keep using for years.",
  346: "For example: Google gives a free month — I used one video for the whole year. There's a way to sign up for a year, but I didn't — because one month lasts, while a year is gone in a flash.",
  347: "I want to create things that are endless, and that I only build once.",
  348: "The Gift Building Process — an AI App",
  349: "I needed to solve one repetitive job: making videos. I used <b>AI vibe coding</b> to build an AI app that packages and produces my product. Then I filmed one video walking through the whole process.",
  350: "G.1",
  351: "Screenshots + a post sharing how to build the app → with the tutorial video attached",
  352: "G.2",
  353: "Run a Zoom: give away the app + walk everyone through it live",
  354: "G.3",
  355: "The people who received it get results → upgrade the app and give it again",
  356: "G.4",
  357: "Package the process into a document — bundle 3 apps into a new combo",
  358: "G.5",
  359: "3,000 customers · 1,000 YouTube follows · A viral post · Real relationships",
  360: "While you're giving gifts away — for every person who comes to collect one, you earn <b>$1.</b> After that I trade the gift for an email, and the AI agent system I set up runs by itself. <b>Set it up once and it runs forever.</b>",
  361: "I've shared before about how to do email marketing… and I'd be glad for the chance to share it with you.",
  362: "Skill 05 · The Marketing Assassin — The $2 Formula",
  363: "Most people immediately think of <b>free gifts.</b> I did too — and people with a voice and a brand convert very easily. One post and a thousand people see it.",
  364: "But I was new. And you, reading this book — maybe you are too, my friend. Without a different marketing strategy, it's very hard to compete with people like that.",
  365: "In the race to the first $1,000 — I had no advantage at all. No channel. No influence. No experience. Not even a decent computer.",
  366: "And yet I made <b>$3,000 and 500 customers</b> in a short stretch of time. The secret is three words: <b>keep helping people.</b>",
  367: "I started by pouring everything I knew into a document — taking care of every single $2 customer. Then one fine day I found a winning product and started promoting it. <b>$10,000 in sales</b> — there you go.",
  368: "<b>The first idea that made me $3,000</b>",
  369: "When ChatGPT came out, I watched people use it like a typing tool. But I noticed something else — <b>a GPT assistant could be packaged into a process and handed to any account to use for free.</b>",
  370: "I spent <b>289K</b> on the <b>Diamond Hook</b> card deck — over 100,000 copies sold worldwide. I read every card, photographed them, fed them to AI to learn from, and created my first hook-writing assistant: <b>ChatGPT Master Hook.</b>",
  371: "A 289K card deck → a free GPT assistant → thousands of users → <b>my first $3,000.</b> No big capital needed — just seeing the opportunity before everyone else.",
  372: "When you doubt, you stay indifferent. When you believe — every resource lines up behind you.",
  373: "People could use it on a free AI account — no upgrade needed. I posted it in groups with a screen-recorded demo. Each account sold for <b>249,000đ, lifetime access.</b>",
  374: "But I didn't sell at 249K from the start. I sold at <b>$1</b> — 30 people. With 30 people I raised it to <b>$5</b> — 100 people. Only then did I go to <b>$10.</b>",
  375: "Done by hand, and $3,000. The part I've never told anyone.",
  376: "It's that the person sharing is the person with authority. ChatGPT was red hot at the time, demand was enormous, so my post went viral. I didn't have to support people much, because it was so easy to use.",
  377: "From that free gift — I started sending people to the products I was promoting. All I cared about was trading the gift for a click. The clicks kept climbing. And in a recent month — I hit <b>$3,100</b> from a product I'd promoted earlier. That's one small piece of my business model.",
  378: "The incident came at the moment I least expected.",
  379: "My Facebook page suddenly went viral. Ten million in traffic poured in over a few days — from Facebook, TikTok, YouTube, everywhere at once. I stood there watching the numbers climb with no idea what to do. No course to sell. No big product prepared. And by the criteria I'd set at the start — launching a course wasn't the direction I wanted. It would eat all my time. And time, for me back then, was worth even more than the opportunity.",
  380: "I had exactly three hours to decide.",
  381: "I opened the laptop, repackaged the document I was already using — edited it, added instructions, exported a PDF. Priced it at <b>$2</b>. Posted it immediately.",
  382: "Fifty people bought at once.",
  383: "I was so surprised I just sat there watching the balance tick up. I raised it to <b>$5</b> — people still bought. Raised it to <b>$10</b> — still didn't stop. I stopped there and started making other products on the same formula: $2, $5, $10. Each one solving one specific, small problem — but something <b>people genuinely needed.</b>",
  384: "And that's when I understood the real lesson, the one I'd never heard anyone say:",
  385: "You don't need a big brand to sell. You just need to solve one problem — no matter how small.",
  386: "More important than the money, more than the revenue from $2 — is what comes after each of those transactions: <b>the email.</b>",
  387: "Every buyer is someone who has already paid me. Even if it's only $2, even if it's only once — they've proven they'll open their wallet. When I send them information about a new affiliate product, the odds they buy again are many times higher than a stranger who's never heard of me. I control that list. It's a customer base <i>I built myself</i> — not dependent on any algorithm or platform.",
  388: "<b>An email list is the real asset of a one-person business.</b>",
  389: "Every day AI ships a new update, people upgrade and pay. The commission I earn — repeating, automatic, even while I sleep. No need to explain from scratch. No need to serve more people.",
  390: "This strategy runs against almost everything people usually do: either give it away free to build an audience, or sell straight at a high price. The middle ground — a small product, extremely cheap, solving a real problem — is almost completely abandoned. And once you own that space, even big brands find it hard to compete.",
  391: "The first dollars will flow in on their own — and after that everything changes completely.",
  392: "Once I had a list of paying customers, I started to see a lever I'd completely missed before.",
  393: "I reached out directly to international AI brands — the platforms I was using and promoting. The message I sent was simple: <i>“I have a paying community. They trust me. I can put information about your product in front of them any time.”</i>",
  394: "I attached real data — number of buyers, email open rates, engagement. No inflation. No empty promises.",
  395: "They look at the data, and they trust it completely.",
  396: "The first booking deals started coming in. I took on <b>5–8 minute</b> promo videos for AI brands — <b>$100 to $300</b> each. Some brands signed for <b>3–5 videos a month</b>. That was the first fixed income I earned from the international market.",
  397: "And then something remarkable happened: after the video went up, the brand ran ads on that same video — and my channel went even more viral. New traffic came in, the email list grew again, more orders followed.",
  398: "The flywheel turns itself: video → ads → traffic → customers → new brands → the next video.",
  399: "And the thing that set me apart — I already had a base of customers who'd paid before, ready to click, ready to buy. Not everyone walks into a negotiation with that.",
  400: "At that point I was running <b>three income streams at once</b> — without hiring a single person:",
  401: "Brand bookings",
  402: "$100–$300 / video · monthly contracts of 3–5 videos",
  403: "Affiliate commission",
  404: "Repeats every month as AI updates — customers upgrade, commission lands by itself",
  405: "$2 products",
  406: "A customer base that keeps growing · an asset that compounds on its own",
  407: "Honestly, at the start I had no idea what to do. Then I remembered something I'd learned from the internet heavyweights around the world: they build hundreds of thousands of email subscribers — <i>purely with gifts.</i>",
  408: "They use a $4 ebook. I thought: I'm not as good as they are yet — but $2 I can do. And that decision opened up a completely new chapter for me.",
  409: "Don't try to start with something big. Start with what you can do today — however small.",
  410: "How to build this whole three-stream system — from the sales page, to automated email, to closing with AI — I've now applied with over 500 people. Here's the next step:",
  411: "The Freedom Code Course",
  412: "In Place of a Thank You",
  413: "So now you know all of my secrets.",
  414: "When I wrote this book, all I thought was… <i>if just one person finds their road — then I've been worth something to the world.</i>",
  415: "You paid for the book, so there's no need to thank me. If the book works for you and you like it enough to recommend it to others — one post online with my name tagged — then I'll consider that today I gained one more friend who knows me through this book.",
  416: "Thank you.",
  417: "It's 2 a.m. right now. I've been typing these lines for three hours into the night. My child is small, there's a lot of work — so this is the time I give to writing.",
  418: "This week I'm running three AI events across the country. I'm writing while you're asleep. But I hope <b>Phong Menly</b> turns out to be a name that's worth something in your life — and never wastes a single second of your time.",
  419: "Part III",
  420: "Pride &amp;<br>The Long Slide Down",
  421: "Celebrating early, and the trap of resting.",
  422: "Chapter 3 · The Long Slide Down",
  423: "It usually hits exactly when you're at your highest. You're doing well — results coming in, confidence rising — and then one day, everything just goes <b>bang</b>.",
  424: "No warning. No clear reason. Just a hollow feeling spreading over everything — and you can't see what you're supposed to do next on your own journey any more.",
  425: "Confidence turns into a sharp blade — and leaves you no way back.",
  426: "When you have nothing, you're not afraid of losing. But once you have something — results, a brand, relationships, money — the only thing you think about is <b>not losing it.</b> And that fear is exactly what locks you up.",
  427: "Things gradually close in. The loop starts. You do less — then results shrink — then you lose motivation — then you do even less. This trap isn't loud. It's silent.",
  428: "The fall never happens at the bottom. It happens at the top — when you think you've arrived.",
  429: "<b>You need to go back to the simplest thing.</b>",
  430: "You can't run on emotion at this point. Emotion is distorted — it magnifies the fear and shrinks what you're capable of. What you need now is to <b>walk through the gaps</b> — look straight at what's missing and handle them one at a time. Don't look far ahead. Just do the one thing you can do today.",
  431: "But more important than any of that — you need to find <b>your guide.</b>",
  432: "Of all your relationships — the one person you must keep isn't your best friend. It's your guide.",
  433: "A friend will comfort you. A guide will show you reality. One tells you you're fine — the other tells you where you're wrong and what to do about it. In a crisis, you don't need comforting. You need <b>reorienting.</b>",
  434: "Think of a lighthouse. It doesn't travel with the ship. It doesn't ask after you or soothe you. It just stands there — and gives light. That's all it has to do. Your guide is the same — one person standing in the right place, and you don't have to fear the dark any more.",
  435: "5 Reasons You Drift Off Course",
  436: "<b>You never set your criteria at the start</b> — every good-looking deal tempts you. With no criteria there's no consistent direction.",
  437: "<b>You scale up resources before you're ready</b> — expanding too fast before the foundation is solid is the quickest way to collapse.",
  438: "<b>You get bored of the simple, repetitive work</b> — but it's exactly that simple, steady work that produces lasting results.",
  439: "<b>You're swayed by your partnerships</b> — the people walking beside you shape your direction more than you think.",
  440: "<b>Your image is too elevated while you want to live simply</b> — that contradiction slowly drains your will and makes you not want to continue.",
  441: "Don't believe the reasons above. I list them only so you can see — they're external factors, and they're always there.",
  442: "Listen, my friend — <b>you're just resting a few days to gather strength for a long road.</b>",
  443: "The moment you start again — is the moment you're stronger than ever.",
  444: "<b>My story — and the mistake I paid for with relationships</b>",
  445: "Once I knew the secret and could sell, I started to really understand the criteria. And a lot of people came to talk to me — thinking about starting over, starting a new business, having tried many places without understanding enough. They needed help.",
  446: "I thought: I've been through this, helping people is a good thing. I gave evidence, analysed the criteria, pointed straight at the mistakes — in the way I thought was most useful.",
  447: "But I was wrong.",
  448: "Everyone's emotions are different. Everyone's thinking is different. And everyone's ego — is different.",
  449: "When I had nothing, whatever I said sat fine with people. But once I was up high — the very same sentence made people feel pressured, dismissed, held back. I didn't mean it that way. But what I meant matters less than <b>how they felt.</b>",
  450: "I lost resources. I lost brothers. There were moments that risked turning into bigger conflict — even a public blow-up. All because I was too blunt, too early, with people who weren't ready to hear it.",
  451: "5 Steps to Come Back &amp; Get Through Any Fall",
  452: "Nobody picks you up but you. If your trousers are falling down, you're the one who has to pull them up — my friend.",
  453: "<b>Fence off your thinking</b> — don't let it run. Shut out the outside noise and pull yourself back to the present.",
  454: "<b>A sheet of paper and a pencil</b> — write down what you're doing well. Cross out whatever is eating your time and resources.",
  455: "<b>Start earning right now</b> — restart from the <b>$2</b> strategy. Let money land in the account — however small, it pulls your energy back.",
  456: "<b>Find the people who never left you</b> — you don't need to do much. Go on Facebook, hit one like — that's enough for both of you to understand. Sometimes I even push myself to go looking for news about them.",
  457: "<b>Step forward from where you stand</b> — use everything you already have. And this time, run straight through the finish line — my friend.",
  458: "You'll meet this again, more than once. Get up and keep walking.",
  459: "On The Road You Walk — There Are Three Kinds of People",
  460: "<b>A command to carry with you:</b><br>— Meeting someone for a day doesn't mean you know them.<br>— Working together for a year doesn't guarantee you're truly close.",
  461: "The people who back you",
  462: "Sometimes all you need is a small circle — people who <b>live well and think well.</b> As for the rest, whether they back you or not — it doesn't matter.",
  463: "Your road — you walk it. Your legs — you stand on them. Head up. Do the right thing and that's enough — the rest doesn't matter.",
  464: "If you're not good at building relationships either — don't worry. <b>If you have value, people will always need you.</b>",
  465: "The people who are indifferent to you",
  466: "They may be indifferent to your message — but they're <b>the easiest people to work with.</b> Very clear about mutual benefit. They're busy with their work — and so are you.",
  467: "When you market, they might ignore it. But the moment it's exactly what they need — they'll show up. All you have to do is <b>understand the need better.</b> That's something I'll go deeper on when I get the chance.",
  468: "The people who throw stones at you",
  469: "Ready with dismissive words. Plenty of times it's annoyed me too — they write, but in reality they know nothing about you.",
  470: "Just let them be. They blow off steam and go back to being whoever they want to be. Let them be themselves — you don't owe them an explanation.",
  471: "The people who back you at first, then disappear",
  472: "Some people support you early on — you feel close to them — and then one day they're gone, or simply no longer beside you.",
  473: "<b>Be glad for them.</b> They're going through a long slide of their own — and they'll get up by themselves. You don't need to worry. The more you worry — the more your advice turns into pressure.",
  474: "My friend — all you need to mind is <b>your own thoughts and feelings.</b> The rest of the world is just the ordinary business that goes on every day.",
  475: "You're on your own — so your energy always has to be strong. Remember that. With me cheering you on, you've got one more person — and the same goes for you.",
  476: "Writing this for you — is also how I get to learn every step again myself.",
  477: "Part IV",
  478: "Cash Flow Drives<br>Traffic",
  479: "What to do when the first small results arrive.",
  480: "Here's the secret.",
  481: "In selling or in business — <b>collect first, sell second</b> is a tactic that never goes out of date.",
  482: "That's the secret, my friend.",
  483: "Part IV · Cash Flow Drives Traffic",
  484: "The $2 Is Done — What Next?",
  485: "I'd bet you get stuck right here. Most people — seeing what others do — copy it: sell something quickly to make the effort worth it, show off the revenue, the orders, the wins, then go hunting for new customers again. A loop that never stops.",
  486: "But you're different. <b>The $2 is a test</b> — it turns traffic into someone who has bought. Not a real customer yet. It's the starting point, not the destination.",
  487: "You need leverage to reach the top. You need a brand. You need people following you — and don't sit waiting for a platform to hand you traffic.",
  488: "Whenever I put out a message, I take everything I know and share it with a small group of 50 people. Then the whole group posts — and instantly that message covers the entire newsfeed of the people who matter most. <b>No ad spend. Just the right people.</b>",
  489: "When you have traffic and you have resources — what you're creating at that point isn't money. It's <b>the shift from “Attract” to “Credibility”.</b> That's the real secret of this game.",
  490: "The 7 Tiers of Customer Loyalty",
  491: "“Big doesn't mean durable. A competitor cutting prices can take your customers any time. The only ones they can't take are the ones who stay out of love.”",
  492: "<b>Superfans</b> — praise you, defend you, recommend you unprompted. No commission, no calculation — purely out of love.",
  493: "<b>Advocates</b> — actively spread your brand to other people.",
  494: "<b>Members</b> — VIP accounts, buying regularly, highly committed.",
  495: "<b>Repeat customers</b> — these are the “real customers”. They've bought a second time or more.",
  496: "<b>One-time buyers</b> — the first barrier is broken. Usually starts with the $2 product.",
  497: "<b>Prospects</b> — they've heard of you, they're interested, they left their details.",
  498: "<b>The market</b> — your target crowd. They don't know who you are yet.",
  499: "Your job isn't to keep finding new customers forever. Your job is to <b>lift customers up one tier at a time.</b>",
  500: "But I have to be honest: I'm <b>reluctant to sell.</b> Not because I don't know how — but because I don't like standing on the “seller” side, looking at someone like a wallet. Every time I'm about to message an offer, I ask myself: <i>“Am I being a nuisance?”</i>",
  501: "Then I realised — that reluctance isn't just personality. It's a sign of <b>carrying too much alone.</b> Making content, caring for customers, chasing traffic, moving people up tiers — running it all solo, however good you are, there comes a point where you're too tired to want to sell at all.",
  502: "It's not that you're lazy. It's not that you're wrong. It's that the system needs more than one person — and here's my solution.",
  503: "<b>Instead of selling — I switched to partnering.</b>",
  504: "I can't outsmart my customers. And nobody is foolish enough to keep buying from me forever without getting something worthwhile back. So I chose another way:",
  505: "<b>Sell one person $2 → then find a way to help that person earn $10 back.</b> Or break even. Or make money the way I do. From there, I created brothers in the Affiliate Network — working together, covering ground together.",
  506: "A competitor takes 10 million from a customer and hands back 1 million. You take $2 from a customer — and deliver $100 of value. Who's going to call you a fool?",
  507: "Serve them wholeheartedly — documents, images, information, everything you have. <b>Then invite them to partner.</b>",
  508: "I often introduce my customers to others. I cheer them on. I do it as a matter of course — no calculating. I'm not good at holding onto customers.",
  509: "I walk with them.",
  510: "Cash Flow First — Traffic Follows",
  511: "This is something I learned from my own experience. <b>How much is enough for you? Set the number first — get the money first — then you'll know what to do next.</b>",
  512: "For example: say I want to run an affiliate project for product A. I work out how much money I need — then go in this order:",
  513: "Negotiate with the brand — lock the terms before you march out.",
  514: "Ask how many people genuinely care — measure demand before building supply.",
  515: "Pick the right way to communicate — raise clicks first, conversion follows.",
  516: "And the thing I always do: <b>find someone who pays up front.</b> It could be a brand, it could be a customer — as long as there's a small amount covering living costs. Then I work without worrying about survival. Not worrying about survival — I work twice as well.",
  517: "To fight a big battle — you need provisions first. Without provisions, every strategy is just theory.",
  518: "<b>Positive cash flow — your strength multiplies. Negative cash flow — everything goes to zero.</b>",
  519: "When money is coming in, every decision you make is sharper. You're not afraid. You don't hesitate. You move faster than any algorithm — because you're in a state of <b>positive cash flow.</b>",
  520: "When money isn't coming in — however excellent your plan, however good your idea — your strength is just a small number multiplied by a negative one. The result is still zero.",
  521: "When things are working — press the advantage. Keep going, keep doing, keep believing. Because at that point you're operating at a frequency nobody can block — not even AI.",
  522: "This isn't something I learned from a book. I learned it looking back at the months I earned the most — I wasn't doing anything different. I was simply <b>in that state.</b>",
  523: "And when that state disappeared — I realised something too: it wasn't because the market changed. It was because I stopped pushing before the right moment.",
  524: "Three Layers of Traffic — Who Are You Working With?",
  525: "Once you have cash flow, it's time to look at the traffic question more precisely. Not all traffic is the same — and failing to tell these three layers apart is why most affiliate marketers never escape the loop.",
  526: "<b>Attraction traffic</b> — strangers who don't know who you are. They came for interesting content. Takes a lot of effort to convert.",
  527: "<b>Credibility traffic</b> — people who've followed you, read you, listened to you. They trust you. When you speak — they listen.",
  528: "<b>Conversion traffic</b> — people who've bought at least once. They know you're not a fraud. They're ready to buy again.",
  529: "I like selling to credibility traffic — because their need is the clearest. Not much persuading required. Just the right timing.",
  530: "You need to know which layer you're working with — because the strategy, the product and the price are completely different at each one. Once that's clear, you'll know <b>which money is going to be yours.</b>",
  531: "The Funnel Code",
  532: "Time to Do the Maths",
  533: "The revenue formula",
  534: "Revenue = Traffic × Average Order Value × Number of Purchases",
  535: "<b>Traffic</b> — Where do you gather it, and what's the fastest way to reach it? The simplest answer: a customer list <b>you own yourself.</b> They can talk to you any time. If you can — use the most manual method of all: speak to each person directly.",
  536: "<b>Average order value</b> — Design complementary products so customers buy more in one go. And there's a counter-intuitive secret: create one wild offer for the first 50 people — then erase every trace of it and keep raising the price. The fewer people who know, the higher the perceived value.",
  537: "<b>Number of purchases</b> — Promote the flagship product, but the <b>repeat-purchase product</b> is something so small nobody thinks of it. Once a customer has bought <b>$2</b> from you — the door is open. From then on, every purchase after that is far easier.",
  538: "Try selling something for just $2–$5. You'll open a door you never imagined.",
  539: "→ <b>Short on traffic?</b> Focus on small customers first.",
  540: "→ <b>Already have small customers?</b> Raise the number of purchases through good care.",
  541: "→ <b>Already have a system &amp; sales page?</b> Only now should you scale cold traffic.",
  542: "Part V · The Climax",
  543: "The System's<br>Game",
  544: "The secret is the system.<br>Play the system's game — and you'll hold everything in your hands.",
  545: "Part V · The System's Game",
  546: "8 Tiers of Earning With AI — The One-Person Road",
  547: "This isn't theory. This is the map I walked — tier by tier, step by step, with nobody holding my hand.",
  548: "<b>$2 product</b> — A small product. A low barrier to buying. It opens the door for everyone to step in.",
  549: "<b>Affiliate commission</b> — Promote other people's products. No capital, no inventory.",
  550: "<b>Bookings from video</b> — Video pulls people in, they book a slot, you get paid.",
  551: "<b>Submit tools / partnerships</b> — Put AI tools on platforms. Partner with brands, build strategic alliances.",
  552: "<b>Website / landing page ads + agents</b> — A system that runs and collects on its own. It earns while you sleep.",
  553: "<b>Agency — high-ticket services</b> — Serving businesses. Fewer clients, more revenue.",
  554: "<b>Mentor / training / coaching</b> — Teach others the road you walked. Value multiplies each time.",
  555: "<b>Vendor / AI SaaS brand</b> — Build your own software. The hardest tier — it demands everything that came before.",
  556: "You can start from several models — but start <b>strategically.</b> Do it in the right order and you can handle every tier.",
  557: "I got it wrong. I started at <b>affiliate tools</b> — the market was far too new, with a lot of people heading the same way. The problem was that so much was free that promoting anything was hard. Users couldn't escape the discount waves from giants like Google.",
  558: "So I chose a different road: <b>$2.</b> And I've laid out every step so you can walk it comfortably.",
  559: "There's a fortune waiting in the six tiers below — before you ever reach tiers 7–8 and touch real freedom.",
  560: "Why did I wait until the end of the book to tell you this secret?",
  561: "Because if I'd said it early — you'd have jumped straight to tier 7 or 8 with no foundation. And you'd fall. Fall hard. Too hard to get back up.",
  562: "I've been through <b>seven tiers.</b> The last one — I didn't step into. Not because I'm not good enough. Because I know who I am, where I stand, and what my capability actually is.",
  563: "This is why I say I'm not a big success — and yet I found freedom at 31. Knowing where you are, who you are, and what you're capable of — that's a form of wisdom too.",
  564: "Sơn Piaz stands on tier 8. You and me — we play the other seven well. Not because we're lesser. Because <b>our starting lines are different.</b>",
  565: "The people who do well at tier 8 have usually mastered affiliate marketing — they generate their own traffic and stay in control from start to finish. When they launch a product, they don't depend on any outside factor.",
  566: "You don't need to be there yet. Do your own tier well — and each tier will lift you to the next.",
  567: "KOL AI SYSTEM",
  568: "If you want to climb tier by tier — with someone genuinely walking beside you.",
  569: "I'll go through every tier with you using simple, practical tactics you can apply straight away. No empty theory. No crazy promises.",
  570: "<b>60 days</b> fighting alongside you — I'm genuinely there at every step.",
  571: "<b>1 year</b> of member privileges in the KOL AI GO GLOBAL community.",
  572: "From rushed and chaotic → to <b>relaxed and free.</b>",
  573: "I'm free now. I did all of this so you'd have a chance to touch it too.",
  574: "Click Here to Join →",
  575: "The Final System — 5 Stages",
  576: "Stage 1",
  577: "Choose Your Industry",
  578: "<b>Pick one thing, do one thing.</b> I dropped cosmetics, consumer goods and TikTok livestreaming to choose AI. The tools may change later — but the system always runs the same way. Apply AI to work that's already producing results → multiply it. No results → multiplying only multiplies the cost.",
  579: "Stage 2",
  580: "Choose Your Product",
  581: "Create <b>one small product</b> — easy to convert, a tiny price — and let it run. Automatic or manual, either is fine. This keeps cash flow positive and your energy burning, morning and night.",
  582: "Stage 3",
  583: "Make Content — The 4 Kinds of AI You Need",
  584: "🖼 <b>AI image generation</b> — Easy, you can do it today.",
  585: "🎬 <b>AI video generation</b> — Easy, needs a bit more creativity.",
  586: "🛒 <b>AI sales page builder</b> — Easy once you have a specific product.",
  587: "⚙️ <b>AI agents — automated operations</b> — Easy once you've used them a few times.",
  588: "Read this back in a few years — the tools will be different. But the system always runs the same way.",
  589: "Stage 4",
  590: "Turn Gifts Into Leads",
  591: "More gifts → more customers. The funnel here is <b>giving gifts to build credibility.</b> Don't try to trick anyone — no customer is naive. There's only the trust they hand you. They buy because of your <b>responsibility and credibility</b> — and later, even if someone isn't satisfied, you'll still be proud of what you did.",
  592: "Stage 5",
  593: "Convert — Get As Close to the Customer As Possible",
  594: "Zalo groups · Zoom · Email marketing · Tutorial videos · $2 / $5 / $10 conversions. At this stage — <b>move fast, don't crawl.</b>",
  595: "<i>Finding marketing hard? Learn, and don't be afraid to try something new. Short on time? Go for high-ticket services — serve fewer people and still secure the income.</i>",
  596: "This isn't the longest book, or the best, or the best-selling. It's <b>the simplest map</b> for you — on your own — to walk step by step toward freedom. I've been there in every chapter, through your whole journey.",
  597: "UP · UP · UP · AND UPPPPP",
  598: "Keep walking and you'll arrive. That's our mantra — my friend.",
  599: "Bonus Section",
  600: "Managing Time — The Secret for Those Walking Alone",
  601: "You don't need to study more. You need <b>those first small results</b> — to keep your energy and stay in the fight every day.",
  602: "Remember the <b>criteria table from Part I</b>? That's the main weapon I use to defend my time:",
  603: "<b>✓ Deals I take:</b> the right industry already running, pays off immediately, uses skills I already have, fits the criteria — even if it's small.",
  604: "<b>✗ Good deals I turn down:</b> however high the income, however attractive — if it breaks the criteria, if it isn't my moment. I say no.",
  605: "<b>Things you do once and use for years</b> are what really save time. A YouTube video, a book, an affiliate system… they all compound over the years.",
  606: "<b>Earn where you already are.</b> I chose Facebook and YouTube because YouTube lets me build the whole system once and use it for years. It was slow at the start — but now <b>nothing can stop it.</b> That's the secret behind the difference.",
  607: "The road is a little longer at the start — but it's the only one that leads to real freedom.",
  608: "Do Less — Do It Right — Then Do It Again",
  609: "<b>Pick one big goal for each stage.</b> This book isn't long — but it holds a lot of strategy. If you're just starting: go from <b>Step 1 · Strategy 1 · Tier 1.</b> Don't skip ahead.",
  610: "Each day — only do the things that are <b>important and not too urgent.</b> There are <b>5 tasks</b> to finish. Complete them one by one — a calm mind, and energy that lasts.",
  611: "The formula for repeating wins",
  612: "Content that wins → <b>do it again.</b><br>A way of closing that wins → <b>do it again.</b><br>A process that saves time → <b>standardise it and do it again.</b>",
  613: "Good people don't do lots of new things — they do the proven thing extremely well.",
  614: "<b>Welcome — this is the first step<br>on your own road to freedom.</b>",
  615: "If you need somewhere that points the right way, someone to ask — come to <b>KOL AI SYSTEM.</b><br>There are brothers walking with you there. You won't be alone any more.",
  616: "Enter KOL AI SYSTEM →",
  617: "Closing Words",
  618: "I'm Handing You This Notebook",
  619: "I'm only a few steps ahead of you. No more than that. But in those few steps — I found something that would otherwise cost you dearly, many times over, and take years to understand.",
  620: "When you have <b>freedom of income</b>, <b>freedom of time</b>, <b>freedom of emotion</b>, <b>freedom of mental health</b>, <b>freedom in your relationships</b> — that's when you can stand above it and see the road. Look around and see everything clearly.",
  621: "Like standing at the top of a slope looking down into the valley — you see the whole map, not just the step in front of you.",
  622: "I don't mean to say you're lesser. I only want to hand you this notebook — to light the road ahead.",
  623: "Instead of living through every mistake yourself — you can click into each chapter and have it made clear. <b>Your time is gold.</b> And I hope this book is the first step — even if only in your thinking — on your road to freedom.",
  624: "The title of this book sounds like a novel. But most of what's inside is real-world business strategy — <b>guerrilla marketing</b> moves proven in practice.",
  625: "I've opened plenty of companies. I crammed thousands of things into my head — books, courses, seminars, this teacher and that one. Now — what's shared in this small book is simple, but it works. And it lights the road ahead of you.",
  626: "THE FREEDOM CODE",
  627: "Live the life you want.",
  628: "Affiliate × AI",
  629: "Are you living…<br><b>or just existing?</b>",
  630: "Start your own road to freedom — leave the place you're standing. Because the most precious things we have are <b>health, time and freedom</b>. Let's open that door together, my friend.",
  631: "From <b>one</b> to <b>number one</b>",
  632: "Phong Menly",
  633: " ← Academy ",
  634: "Cover"
};
